/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.trabalhoffinalaliciageovanna;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class FrnListarTodosAlunos extends javax.swing.JDialog {
    private List<Aluno> listaAlunos;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrnListarTodosAlunos.class.getName());

    /**
     * Creates new form FrnListarTodosAlunos
     */
    public FrnListarTodosAlunos(java.awt.Frame parent, boolean modal,List<Aluno> listaRecebida) { 
        super(parent, modal);
        initComponents();
        this.listaAlunos = listaRecebida;
        this.setSize(540, 380);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Color cor = new Color(238, 213, 210);
        JPanel background = (JPanel) this.getContentPane();
        background.setBackground(cor);
        preencherLista();
    }

    private FrnListarTodosAlunos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void preencherLista() {
      StringBuilder sb = new StringBuilder();// cria uma string longa,  que mostrará os dados dos alunos
      // Classe que formata data
      SimpleDateFormat sDdateFormate = new SimpleDateFormat("dd/MM/yyyy");
      
        if (this.listaAlunos.isEmpty()) {
            sb.append("A lista de alunos está vazia.");
        } else {
            for (Aluno aluno : this.listaAlunos) {
                String dataNascimentoFormatada;
                try {
                    // Formatar a data se o objeto não for nulo
                    if (aluno.getDataNasc() != null) {
                        dataNascimentoFormatada = sDdateFormate.format(aluno.getDataNasc());
                    } else {
                        dataNascimentoFormatada = "Data não informada";
                    }
                } catch (Exception e) {
                     dataNascimentoFormatada = "Data inválida";
                }
                // Formatação para que todas as informações de cada aluno
                sb.append("======================================================================\n");
                sb.append("Matrícula: ").append(aluno.getMatricula()).append("\n");
                sb.append("Nome: ").append(aluno.getNome()).append("\n");
                sb.append("Data de Nascimento: ").append(dataNascimentoFormatada).append("\n"); 
                sb.append("CPF: ").append(aluno.getCPF()).append("\n");
                sb.append("Telefone: ").append(aluno.getTelefone()).append("\n\n");
            }
        }

        // Inserir a string formatada no JTextArea
        jTextAreaAlunos.setText(sb.toString());
        // Garante que a barra de rolagem comece no topo
        jTextAreaAlunos.setCaretPosition(0); 
        // Garantir que não seja modificado ou apagado
        jTextAreaAlunos.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlunos = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Alunos");

        jTextAreaAlunos.setBackground(new java.awt.Color(238, 213, 210));
        jTextAreaAlunos.setSelectionColor(new java.awt.Color(255, 218, 196));
        jScrollPane1.setViewportView(jTextAreaAlunos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrnListarTodosAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextAreaAlunos;
    // End of variables declaration//GEN-END:variables
}
