/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhoffinalaliciageovanna;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DTIC
 */
public class FrnPrincipal2 extends javax.swing.JFrame {

    List<Aluno> listaAlunos = new ArrayList<>();

    /**
     *
     * Creates new form FrnPrincipal2
     */
    public FrnPrincipal2() {
        initComponents();
        setResizable(false);
        setSize(540, 380);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matricula = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        datanasc = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));

        matricula.setText("Matrícula:");

        nome.setText("Nome:");

        datanasc.setText("Data nascimento:");

        idade.setText("Idade:");

        telefone.setText("Telefone:");

        cpf.setText("CPF:");

        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataNascFocusLost(evt);
            }
        });
        jFormattedTextFieldDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNascActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });

        jTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdadeActionPerformed(evt);
            }
        });

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });

        jButtonPesquisar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("jButton1");

        jButtonInserir.setBackground(new java.awt.Color(153, 153, 255));
        jButtonInserir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonListar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonListar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListar.setText("Listar ");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jButtonApagar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonApagar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApagar.setText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idade))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldDataNasc)
                                .addComponent(jTextFieldIdade)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nome)
                                        .addComponent(matricula)
                                        .addComponent(cpf)))
                                .addComponent(telefone, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldMatricula)
                                .addComponent(jTextFieldNome)
                                .addComponent(jFormattedTextFieldCPF)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonApagar)
                    .addComponent(jButtonInserir)
                    .addComponent(jButtonListar)
                    .addComponent(jButton3))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Aluno aluno = new Aluno();
        SimpleDateFormat sDdateFormate = new SimpleDateFormat("dd/MM/yyyy");

        //verifica se a matrícula do aluno foi preenchida
        if (jTextFieldMatricula.getText().trim().isEmpty()|| 
            jTextFieldNome.getText().trim().isEmpty() || 
            jFormattedTextFieldCPF.getText().trim().isEmpty() ||
            jFormattedTextFieldDataNasc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "É necessário preencher todos os campos!", "Informação", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            //coleta a matrícula do aluno
            String matriculaA = jTextFieldMatricula.getText();
            aluno.setMatricula(matriculaA);
            //coleta o nome do aluno
            String nomeA = jTextFieldNome.getText();
            aluno.setNome(nomeA);
            //coleta o CPF do aluno
            String cpfA = jFormattedTextFieldCPF.getText();
            aluno.setCPF(cpfA);
            // Coleta a data de nascimento e calcula a idade para sincronizar no objeto Aluno
            try {
                String dataNascA = jFormattedTextFieldDataNasc.getText();
                Date dataNasc = sDdateFormate.parse(dataNascA);
                aluno.setDataNasc(dataNasc);

                // Calcula e seta a idade no objeto Aluno (usando o mesmo código do focusLost para consistência)
                LocalDate nascAlunoDate = dataNasc.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                LocalDate dataAtual = LocalDate.now();
                Period periodo = Period.between(nascAlunoDate, dataAtual);
                int idadeCalculada = periodo.getYears();
                aluno.setIdade(idadeCalculada);  // Agora o objeto Aluno tem a idade correta

            } catch (ParseException ex) {
                Logger.getLogger(FrnPrincipal2.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Data de nascimento inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;  // Sai se houver erro de parsing
            }
            //coleta o telefone do aluno(opcional)
            String telefoneA = jFormattedTextFieldTelefone.getText();
            aluno.setTelefone(telefoneA);
        }
        
        if (!alunoComMatriculaEstaNaLista(listaAlunos, aluno.getMatricula())) {  // Passa a matrícula como parâmetro (veja Problema 4)
            JOptionPane.showMessageDialog(null, "O aluno foi adicionado na lista de alunos com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            listaAlunos.add(aluno);
            // TODO: Implementar salvamento em CSV aqui, se necessário
        }
        
        // Limpar os campos depois de salvar 
        jTextFieldMatricula.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setValue(null);
        jFormattedTextFieldTelefone.setValue(null);
        jFormattedTextFieldDataNasc.setValue(null);
        jTextFieldIdade.setText("");
    }//GEN-LAST:event_jButtonSalvarActionPerformed
    
    private boolean alunoComMatriculaEstaNaLista(List<Aluno> listaAlunos, String matricula) {
        for (Aluno aluno : listaAlunos) {
            if (aluno.getMatricula().equals(matricula)) {
                JOptionPane.showMessageDialog(null, "Já existe um aluno com a matrícula " + matricula + "!", "Informação", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        }
        return false;
    }

    /*
add (int Index, E element) //adiciona em um local especifico
remove(Object o) //remove um elemento especificado
add(List nameList)   //adiciona ao final da lista 
     */
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        FrnPesquisa fp = new FrnPesquisa(this, true, this.listaAlunos);
        fp.setVisible(true); 
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jFormattedTextFieldDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNascActionPerformed

    private void jTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdadeActionPerformed

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        
        //declaração de variáveis
        int idadeAluno;
        int menorIdade;
        int maiorIdade = 0;
        
        Period periodo;
        Date nascA;
        Aluno a; 
        LocalDate dataAtual, nascAlunoDate;
        
        //coleta a data atual
        dataAtual = LocalDate.now();
        
        //Calcula a idade do primeiro aluno na lista para comparação com as demais
        a = listaAlunos.get(0);
        nascA = a.getDataNasc();
        nascAlunoDate = nascA.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        periodo = Period.between(nascAlunoDate, dataAtual);
        idadeAluno = periodo.getYears();
        menorIdade = idadeAluno;
        
        for (int i = 0; i < listaAlunos.size(); i++){
            //pega os dados do aluno com indice i
            a = listaAlunos.get(i);
            
            //Formata a data de nascimento inserida e converte de java.util.date para LocalDate
            nascA = a.getDataNasc();
            nascAlunoDate = nascA.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            //calcula a diferença entre as datas e armazena na idade do aluno
            periodo = Period.between(nascAlunoDate, dataAtual);
            idadeAluno = periodo.getYears();
            
            //analisa qual é o aluno mais novo e o mais velho
            if (idadeAluno < menorIdade){
                menorIdade = idadeAluno;
            }
            
            if(idadeAluno > maiorIdade){
                maiorIdade = idadeAluno;
            }
        }
        
        //transforma as idades em strings para exibição
        String strMenorId = String.valueOf(menorIdade);
        String strMaiorId = String.valueOf(maiorIdade);
        
        //painel de exibição da mensagem
        JOptionPane.showMessageDialog(null, "O aluno mais novo possui " + strMenorId + " anos e o mais velho possui " + strMaiorId, "Análise de idade", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jFormattedTextFieldDataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascFocusLost
        //cria uma formatação de data
        SimpleDateFormat sDdateFormate = new SimpleDateFormat("dd/MM/YYYY");
             
       //coleta a data de nascimento inserida
        String dataNascA = jFormattedTextFieldDataNasc.getText();
        
        try {
                //Formata a data de nascimento inserida e converte de java.util.date para LocalDate
                Date dataNascAluno = sDdateFormate.parse(dataNascA);               
                LocalDate nascAlunoDate = dataNascAluno.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    
                //coleta a data atual
                LocalDate dataAtual = LocalDate.now();

                //calcula a diferença entre as datas e armazena na idade do aluno
                Period periodo = Period.between(nascAlunoDate, dataAtual);
                int idadeAluno = periodo.getYears();

                String strIdade = String.valueOf(idadeAluno);
                jTextFieldIdade.setText(strIdade);
                //esse campo não pode ser modificado
                jTextFieldIdade.setEditable(false);
                                        
            } catch (ParseException ex) {
                Logger.getLogger(FrnPrincipal2.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jFormattedTextFieldDataNascFocusLost

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        // TODO add your handling code here:                                          
        FrnRemover frm = new FrnRemover(listaAlunos);
        frm.setVisible(true);

    }//GEN-LAST:event_jButtonApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrnPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrnPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrnPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrnPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrnPrincipal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel datanasc;
    private javax.swing.JLabel idade;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JLabel matricula;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
