/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.trabalhoffinalaliciageovanna;

import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author geova
 */
public class FrnRemove extends javax.swing.JDialog {
    private List<Aluno> listaAlunos;
    private AlunoDAO alunoDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrnRemove.class.getName());

    /**
     * Creates new form FrnRemove
     */
    public FrnRemove(java.awt.Frame parent, boolean modal,List<Aluno> listaRecebida, AlunoDAO alunoDAO) {
        super(parent, modal);
        initComponents();
        //pega a lista de alunos do FrnPrincipal2 e dimensiona a tela
        this.listaAlunos = listaRecebida;
        this.alunoDAO = alunoDAO;
        this.setSize(540, 380);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    private FrnRemove() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    // Método de remoção por matrícula
    public List<Aluno> removerAlunoPorMatricula(List<Aluno> alunos, String matricula) {
        if (alunos != null && matricula != null && !matricula.isEmpty()) {
            alunos.removeIf(a -> a.getMatricula().equals(matricula));
        }
        return alunos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldMatriculaRemover = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNomeRemover = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpfRemover = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CPF: ");

        jFormattedTextFieldMatriculaRemover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldMatriculaRemover.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldMatriculaRemoverFocusLost(evt);
            }
        });
        jFormattedTextFieldMatriculaRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMatriculaRemoverActionPerformed(evt);
            }
        });

        jFormattedTextFieldNomeRemover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldNomeRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNomeRemoverActionPerformed(evt);
            }
        });

        jFormattedTextFieldCpfRemover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldCpfRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCpfRemoverActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Remoção de Aluno");

        jButtonRemover.setBackground(new java.awt.Color(153, 153, 255));
        jButtonRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Matricula: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldNomeRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCpfRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldMatriculaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldMatriculaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemover))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNomeRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCpfRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldMatriculaRemoverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMatriculaRemoverFocusLost
        // TODO add your handling code here:
        String matricula = jFormattedTextFieldMatriculaRemover.getText();
        if (listaAlunos != null && !matricula.isEmpty()) {
            Optional<Aluno> alunoOpt = listaAlunos.stream()
            .filter(a -> a.getMatricula().equals(matricula))
            .findFirst();
            if (alunoOpt.isPresent()) {
                Aluno aluno = alunoOpt.get();
                jFormattedTextFieldNomeRemover.setText(aluno.getNome());
                jFormattedTextFieldCpfRemover.setText(aluno.getCPF());
            } else {
                jFormattedTextFieldNomeRemover.setText("");
                jFormattedTextFieldCpfRemover.setText("");
            }
        }
    }//GEN-LAST:event_jFormattedTextFieldMatriculaRemoverFocusLost

    private void jFormattedTextFieldMatriculaRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMatriculaRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldMatriculaRemoverActionPerformed

    private void jFormattedTextFieldNomeRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNomeRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNomeRemoverActionPerformed

    private void jFormattedTextFieldCpfRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCpfRemoverActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        String matricula = jFormattedTextFieldMatriculaRemover.getText();
        if (matricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite uma matrícula.");
            return;
        }
        boolean removed = listaAlunos.removeIf(a -> a.getMatricula().equals(matricula));
        

    // 1) Tenta remover do banco
    boolean removidoBanco = false;
    try {
        removidoBanco = alunoDAO.excluirHibernate(matricula);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao remover do banco: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
        if (removed || removidoBanco) {
            JOptionPane.showMessageDialog(this, "Aluno removido com sucesso!");
            jFormattedTextFieldMatriculaRemover.setText("");
            jFormattedTextFieldNomeRemover.setText("");
            jFormattedTextFieldCpfRemover.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrnRemove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfRemover;
    private javax.swing.JFormattedTextField jFormattedTextFieldMatriculaRemover;
    private javax.swing.JFormattedTextField jFormattedTextFieldNomeRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
